spring.application.name=paylance-backend
# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/paylance_db
spring.datasource.username=paylance_user
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT (optional)
jwt.secret=YourSecretKey
jwt.expiration=3600000
